# Refactored DuoFormer - Default Configuration
# For general medical image classification tasks
# Modify as needed for your specific application

exp_name: duoformer_default
seed: 42
device: cuda
mixed_precision: false

backbone:
  name: resnet50
  pretrained: true
  freeze: true
  weights: DEFAULT

transformer:
  depth: 12
  embed_dim: 768
  num_heads: 12
  mlp_ratio: 4.0
  qkv_bias: true
  qk_norm: false
  attn_drop_rate: 0.0
  proj_drop_rate: 0.0
  drop_path_rate: 0.0
  init_values: null

multiscale:
  num_layers: 2
  num_patches: 49
  proj_dim: 768
  scale_token: random
  patch_attn: true

training:
  learning_rate: 0.0001
  weight_decay: 0.0001
  optimizer: adamw
  momentum: 0.9
  scheduler: cosine
  warmup_epochs: 5
  min_lr: 1.0e-06
  epochs: 100
  batch_size: 32
  num_workers: 4
  pin_memory: true
  label_smoothing: 0.1
  mixup_alpha: 0.0
  cutmix_alpha: 0.0
  save_freq: 5
  keep_last_n: 3
  patience: 20
  min_delta: 0.0001

data:
  dataset_name: medical_imaging
  data_dir: ./data
  num_classes: 10  # Adjust for your classification task
  image_size: 224
  normalize_mean:
  - 0.485
  - 0.456
  - 0.406
  normalize_std:
  - 0.229
  - 0.224
  - 0.225
  use_augmentation: true
  random_flip: true
  random_rotation: 10
  color_jitter: true
  brightness: 0.2
  contrast: 0.2
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15

logging:
  log_dir: ./logs
  tensorboard_dir: ./runs
  log_interval: 10
  use_wandb: false
  wandb_project: duoformer
  wandb_entity: null
  use_mlflow: false
  mlflow_tracking_uri: http://localhost:5000
  mlflow_experiment_name: duoformer

