# Refactored DuoFormer - Performance Configuration
# For best model performance on medical imaging tasks

exp_name: duoformer_performance
seed: 42
device: cuda
mixed_precision: true

backbone:
  name: resnet50
  pretrained: true
  freeze: false
  weights: DEFAULT

transformer:
  depth: 12
  embed_dim: 768
  num_heads: 12
  mlp_ratio: 4.0
  attn_drop_rate: 0.1
  proj_drop_rate: 0.1
  drop_path_rate: 0.1

multiscale:
  num_layers: 4
  num_patches: 49
  proj_dim: 768

training:
  learning_rate: 0.0001
  weight_decay: 0.0001
  optimizer: adamw
  scheduler: cosine
  warmup_epochs: 10
  epochs: 200
  batch_size: 16
  num_workers: 8
  patience: 30

data:
  dataset_name: medical_imaging
  data_dir: ./data
  num_classes: 10  # Adjust for your classification task
  image_size: 224
  use_augmentation: true
  random_flip: true
  random_rotation: 15
  color_jitter: true
  brightness: 0.3
  contrast: 0.3

logging:
  log_dir: ./logs
  tensorboard_dir: ./runs
  log_interval: 5

